# .air.server.toml
[build]
  cmd = "go build -o ./tmp/main cmd/server/main.go"
  bin = "./tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  log = "air_errors.log"

[watch]
  # 監視するディレクトリ
  dirs = ["cmd/server", "internal", "pkg", "api"]

  # 除外するファイルやディレクトリ
  exclude_dirs = ["vendor", "tmp"]

  # 監視するファイルの拡張子
  extensions = [".go"]

[log]
  level = "debug"
